### ISSUE TITLE
Add example of running task of your choice to documenation

### ISSUE THREAD

**Issue by kylemhall** [elstudio/actions-js-build#10]
The documentation states:
> Set the workflow `args` arguments to run the tasks of your choice.

But provides no example, could you add one?

Thanks!

**Comment by dmytrosh0** [comment]
Hi @kylemhall !
In our project at this moment we added custom build task with Gulp. We have experimented with some syntax solutions and have gotten right one. I hope it will be usefull for you or for someone else :)

```
jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Compile with Gulp
      uses: elstudio/actions-js-build/build@v2
      with:
        args: build
```
With this code we launch task `gulp build`.
