### ISSUE TITLE
Run Grunt Task

### ISSUE THREAD

**Issue by markharrison** [elstudio/actions-js-build#19]
Im passing a specific tasks to run

```
    - name: Compile with Grunt
      uses: elstudio/actions-js-build/build@v4  
      with:
        args: build
```

Doesn't work and I get this the output

Warning: Unexpected input(s) 'args', valid inputs are ['wdPath', 'debug']

----

I found it works with build@v2
