### ISSUE TITLE
Allow specifying a custom commit message

### ISSUE THREAD

**Issue by nyancrimew** [elstudio/actions-js-build#3]
Hey, thanks for these great actions! I'm using the commit action only and would love to be able to specify my own commit message so it makes more sense in the context I'm using it.

**Comment by elstudio** [comment]
Super idea!

I’ve just added that, through an input named `commitMessage`. Have a look at the `v2-beta` branch to try it out.

Let me know what you think.

And thanks for the suggestion!

**Comment by winzig** [comment]
@elstudio I'm trying to use the custom commit message, loading the commit action @v2, but it still seems to be using the default commit message. My template:

```
    - name: Commit changes
      if: success()
      uses: elstudio/actions-js-build/commit@v2
      with:
        commitMessage: Gulp built CSS and JS
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Any idea what I'm doing wrong here? Thank you!
